version: "3.8"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - volumedb:/var/lib/db
    ports:
      - 5432:5432
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  volumedb:
